export const orders = [
  {
    _id: 1,
    number: '034535',
    date: 'Сегодня, 16:20 i-GMT+3',
    title: 'Death Star Starship Main бургер',
    products: [
      'https://code.s3.yandex.net/react/code/bun-02.png',
      'https://code.s3.yandex.net/react/code/sauce-01.png',
      'https://code.s3.yandex.net/react/code/meat-02.png',
      'https://code.s3.yandex.net/react/code/meat-04.png',
      'https://code.s3.yandex.net/react/code/mineral_rings.png',
    ],
    price: 23477,
    completed: false,
  },
  {
    _id: 2,
    number: '034534',
    date: 'Сегодня, 13:20 i-GMT+3',
    title: 'Interstellar бургер',
    products: [
      'https://code.s3.yandex.net/react/code/bun-01.png',
      'https://code.s3.yandex.net/react/code/sauce-01.png',
      'https://code.s3.yandex.net/react/code/sauce-03.png',
      'https://code.s3.yandex.net/react/code/meat-01.png',
      'https://code.s3.yandex.net/react/code/mineral_rings.png',
      'https://code.s3.yandex.net/react/code/sp_1.png',
    ],
    price: 56083,
    completed: false,
  },
  {
    _id: 3,
    number: '034533',
    date: 'Вчера, 13:50 i-GMT+3',
    title: 'Black Hole Singularity острый бургер',
    products: [
      'https://code.s3.yandex.net/react/code/bun-01.png',
      'https://code.s3.yandex.net/react/code/sauce-01.png',
      'https://code.s3.yandex.net/react/code/meat-04.png',
      'https://code.s3.yandex.net/react/code/core.png',
    ],
    price: 56709,
    completed: true,
  },
  {
    _id: 4,
    number: '034532',
    date: 'Вчера, 18:34 i-GMT+3',
    title: 'Supernova Infinity бургер',
    products: [
      'https://code.s3.yandex.net/react/code/bun-02.png',
      'https://code.s3.yandex.net/react/code/mineral_rings.png',
      'https://code.s3.yandex.net/react/code/salad.png',
      'https://code.s3.yandex.net/react/code/meat-04.png',
      'https://code.s3.yandex.net/react/code/core.png',
      'https://code.s3.yandex.net/react/code/meat-02.png',
      'https://code.s3.yandex.net/react/code/bun-01.png',
      'https://code.s3.yandex.net/react/code/sauce-01.png',
      'https://code.s3.yandex.net/react/code/core.png',
    ],
    price: 567880,
    completed: true,
  },
  {
    _id: 5,
    number: '034531',
    date: '1 день назад, 16:07 i-GMT+3',
    title: 'Starship Main бургер',
    products: [
      'https://code.s3.yandex.net/react/code/bun-02.png',
      'https://code.s3.yandex.net/react/code/meat-04.png',
      'https://code.s3.yandex.net/react/code/mineral_rings.png',
      'https://code.s3.yandex.net/react/code/sauce-04.png',
    ],
    price: 9078,
    completed: false,
  },
  {
    _id: 6,
    number: '034530',
    date: '1 день назад, 20:03 i-GMT+3',
    title: 'Infinity бургер',
    products: [
      'https://code.s3.yandex.net/react/code/bun-01.png',
      'https://code.s3.yandex.net/react/code/sauce-01.png',
      'https://code.s3.yandex.net/react/code/meat-02.png',
    ],
    price: 8976,
    completed: true,
  },
  {
    _id: 7,
    number: '034529',
    date: '2 дня назад, 21:53 i-GMT+3',
    title: 'Singularity бургер',
    products: [
      'https://code.s3.yandex.net/react/code/bun-01.png',
      'https://code.s3.yandex.net/react/code/sauce-01.png',
      'https://code.s3.yandex.net/react/code/meat-03.png',
      'https://code.s3.yandex.net/react/code/core.png',
      'https://code.s3.yandex.net/react/code/mineral_rings.png',
      'https://code.s3.yandex.net/react/code/sp_1.png',
      'https://code.s3.yandex.net/react/code/meat-01.png',
    ],
    price: 6483678,
    completed: false,
  },
];
